// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/chat.proto

package com.example.chatroom.grpc.proto;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ErrorInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ErrorInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020proto/chat.proto\",\n\007Message\022\020\n\010clientI" +
      "d\030\001 \001(\t\022\017\n\007content\030\002 \001(\t\"0\n\tErrorInfo\022\022\n" +
      "\nsuccessful\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"\036\n\nCl" +
      "ientInfo\022\020\n\010clientId\030\001 \001(\t2P\n\013ChatServic" +
      "e\022#\n\010register\022\013.ClientInfo\032\010.Message0\001\022\034" +
      "\n\004send\022\010.Message\032\n.ErrorInfoB#\n\037com.exam" +
      "ple.chatroom.grpc.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "ClientId", "Content", });
    internal_static_ErrorInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ErrorInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ErrorInfo_descriptor,
        new java.lang.String[] { "Successful", "Message", });
    internal_static_ClientInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ClientInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientInfo_descriptor,
        new java.lang.String[] { "ClientId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
