// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/chat.proto

package com.example.chatroom.grpc.proto;

public interface ClientInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientId = 1;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <code>string clientId = 1;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();
}
