// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/chat.proto

package com.example.chatroom.grpc.proto;

public interface ErrorInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ErrorInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool successful = 1;</code>
   * @return The successful.
   */
  boolean getSuccessful();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
